### ISSUE TITLE
With Pixelmon Generations - Crash When Breeding

### ISSUE THREAD

**Issue by Atlasrune** [BeetoGuy/ApricornTreeFarm#5]
[15:12:09] [Server thread/ERROR] [FML]: Exception caught during firing event com.pixelmonmod.pixelmon.api.events.BreedEvent$MakeEgg@338c0550:
java.lang.NoSuchMethodError: com.pixelmonmod.pixelmon.storage.PlayerPartyStorage.getShinyCharm()Lcom/pixelmonmod/pixelmon/enums/EnumShinyCharm;
        at apritree.event.ShinyPokemonEventHandler.onPixelmonBred(ShinyPokemonEventHandler.java:57) ~[ShinyPokemonEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_83_ShinyPokemonEventHandler_onPixelmonBred_MakeEgg.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateStatus(TileEntityRanchBlock.java:242) ~[TileEntityRanchBlock.class:8.1.2]
        at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateBreeding(TileEntityRanchBlock.java:222) ~[TileEntityRanchBlock.class:8.1.2]
        at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_272]
        at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.func_73660_a(TileEntityRanchBlock.java:168) [TileEntityRanchBlock.class:8.1.2]
        at net.minecraft.world.World.func_72939_s(World.java:1838) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[15:12:09] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[15:12:09] [Server thread/ERROR] [FML]: 0: NORMAL
[15:12:09] [Server thread/ERROR] [FML]: 1: ASM: apritree.event.ShinyPokemonEventHandler@457194f1 onPixelmonBred(Lcom/pixelmonmod/pixelmon/api/events/BreedEvent$MakeEgg;)V
[15:12:09] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NoSuchMethodError: com.pixelmonmod.pixelmon.storage.PlayerPartyStorage.getShinyCharm()Lcom/pixelmonmod/pixelmon/enums/EnumShinyCharm;
        at apritree.event.ShinyPokemonEventHandler.onPixelmonBred(ShinyPokemonEventHandler.java:57) ~[ShinyPokemonEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_83_ShinyPokemonEventHandler_onPixelmonBred_MakeEgg.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateStatus(TileEntityRanchBlock.java:242) ~[TileEntityRanchBlock.class:8.1.2]
        at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.updateBreeding(TileEntityRanchBlock.java:222) ~[TileEntityRanchBlock.class:8.1.2]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_272]
        at com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityRanchBlock.func_73660_a(TileEntityRanchBlock.java:168) ~[TileEntityRanchBlock.class:8.1.2]
        at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[15:12:09] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/minecraft/Pixelmon/./crash-reports/crash-2020-11-09_15.12.09-server.txt

Looks like Apritree is checking for the shiny charm, but no shiny charm exists in the current version of Pixelmon.

**Comment by BeetoGuy** [comment]
Pixelmon Generations isn't officially supported by this mod, as I build my addons on Pixelmon Reforged.
